"""add_priority_due_date_to_tasks

Revision ID: 499a4fa37adc
Revises: bb9f0cc3c251
Create Date: 2026-06-27 00:36:24.400864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499a4fa37adc'
down_revision: Union[str, Sequence[str], None] = 'bb9f0cc3c251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add priority as nullable first so existing rows don't cause NOT NULL violation
    op.add_column('tasks', sa.Column('priority', sa.String(length=20), nullable=True))
    op.add_column('tasks', sa.Column('due_date', sa.Date(), nullable=True))
    # Backfill existing rows with a sensible default
    op.execute("UPDATE tasks SET priority = 'medium' WHERE priority IS NULL")
    # Now enforce NOT NULL
    op.alter_column('tasks', 'priority', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
